name: Fake 50 Commits to All Repos

on:
  schedule:
    - cron: '0 4 * * *'  # Tiap hari jam 4 pagi UTC
  workflow_dispatch:

jobs:
  fake_commits:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GH_PAT }}
      USER: neroxkira
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "neroxmira"
          git config --global user.email "junsganz@gmail.com"

      - name: Get All Public Repos & Commit
        run: |
          repos=$(curl -s "https://api.github.com/users/$USER/repos?per_page=100" | jq -r '.[].full_name')

          for repo in $repos; do
            echo ">>> Cloning $repo"
            git clone https://x-access-token:$TOKEN@github.com/$repo.git
            cd $(basename "$repo")

            # Commit 20x
            for i in $(seq 1 $((RANDOM % 51 + 50))); do
              echo "$(date) - commit $i" >> log.txt
              git add log.txt
              git commit -m "bot: fake commit $i"
            done

            git push
            cd ..
            rm -rf $(basename "$repo")
          done
